Set kernel_interface_ready for loopback
MERAprojects/ops-portd pull request #1
Opened 2016-09-22 11:52 UTC by stroykov

Set kernel_interface_ready to "true" after dummy
interface is created in kernel. It is needed for
those processes/services who needs kernel
configuration done to use the loopback.

Tags: fix, dev

Change-Id: I931e2c8ef1b1c02d39d4cb2af0ea6b23a3210d5b
Signed-off-by: Nikolay Stroykov <stroykov@mera.ru>

2016-10-10 12:18 UTC, apolovin commented on src/portd.c
>              return false;
wrong return semantics: either true/false, or EXIT_SUCCESS (see below)/EXIT_FAILURE

2016-10-10 12:19 UTC, apolovin requested changes
portd_reconfig_ns_loopback: harmonize return code

2016-10-10 14:10 UTC, apolovin approved these changes

2016-10-10 14:16 UTC, stroykov commented
https://review.openswitch.net/13895

2016-11-08 09:50 UTC, vkarpov commented
Merged into meraswitch/devel/master.

2016-11-08 09:50 UTC, closed without merging